services:
#    web_site.example:
#        class: WebSiteBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    admin.lead:
        class: WebSiteBundle\Admin\LeadAdmin
        arguments: [~, WebSiteBundle\Entity\Lead, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Lead }

    admin.contact:
        class: WebSiteBundle\Admin\ContactAdmin
        arguments: [~, WebSiteBundle\Entity\Contact, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Contact }
