web_site:
    resource: "@WebSiteBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    requirements:
        _locale: es|en|cat

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /es
        permanent: true

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
#public:
#    resource: "@PublicBundle/Controller/"
#    type:     annotation
#    prefix:   /{_locale}/
#    requirements:
#        _locale: es|en|cat
